# Generated by Django 5.2 on 2025-04-22 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Plano',
                'verbose_name_plural': 'Categorias de Planos',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_expiracao', models.DateTimeField()),
                ('renovacao_automatica', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura de Produto',
                'verbose_name_plural': 'Assinaturas de Produtos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('recurso_acessado', models.CharField(max_length=255)),
                ('duracao_segundos', models.PositiveIntegerField(default=0)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_uso', to='dashboard.assinaturaproduto')),
            ],
            options={
                'verbose_name': 'Histórico de Uso',
                'verbose_name_plural': 'Históricos de Uso',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField()),
                ('descricao_curta', models.CharField(blank=True, max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('assinatura', 'Assinatura Mensal'), ('licenca', 'Licença Anual'), ('servico', 'Serviço Único')], default='assinatura', max_length=20)),
                ('duracao_dias', models.PositiveIntegerField(default=30, help_text='Duração em dias da assinatura ou licença')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('destaque', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('usuarios_permitidos', models.PositiveIntegerField(default=1, help_text='Quantidade de usuários permitidos')),
                ('armazenamento_gb', models.PositiveIntegerField(default=5, help_text='Espaço de armazenamento em GB')),
                ('permite_exportacao', models.BooleanField(default=False)),
                ('permite_api', models.BooleanField(default=False)),
                ('suporte_24h', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categoriaplano')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='assinaturaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='dashboard.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='assinaturaproduto',
            unique_together={('usuario', 'produto')},
        ),
    ]
