# Generated by Django 5.2 on 2025-04-23 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_data_cadastro_alter_cliente_email_and_more'),
        ('produtos', '0002_alter_produto_descricao_alter_produto_estoque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MetodoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Fixa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Método de Envio',
                'verbose_name_plural': 'Métodos de Envio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email do Cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Cliente')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pagamento Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('endereco_entrega', models.TextField(blank=True, null=True, verbose_name='Endereço de Entrega')),
                ('cidade_entrega', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado_entrega', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep_entrega', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)')),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Frete')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('codigo_rastreamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Rastreamento')),
                ('cliente_cadastrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes.clienteempresa', verbose_name='Cliente Cadastrado')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='vendas.formapagamento', verbose_name='Forma de Pagamento')),
                ('metodo_envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='vendas.metodoenvio', verbose_name='Método de Envio')),
                ('usuario_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='produtos.produtoempresa', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
                'ordering': ['produto__nome'],
            },
        ),
    ]
