# Generated by Django 5.2 on 2025-04-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_data_cadastro_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteempresa',
            name='endereco_adicional',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Endereço Adicional'),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='endereco_principal',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Endereço Principal'),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='endereco_secundario',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Endereço Secundário'),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='telefone_secundario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário'),
        ),
    ]
