# Generated by Django 5.2 on 2025-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteempresa',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='endereco_estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
