# Generated by Django 5.2 on 2025-04-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_create_default_groups'),
        ('usuarios', '0002_create_user_groups'),
    ]

    operations = [
    ]
